import type { ExpectedField } from "@/lib/import/expected-field";
import {
  followUpSlotDateHeaderAliases,
  followUpSlotDateHeaderAr,
  followUpSlotNoteHeaderAliases,
  followUpSlotNoteHeaderAr,
} from "@/lib/import/follow-up-slot-columns";

/** استيراد عملاء جدد — صف مسطّح؛ خانة ١ للربط اليدوي، وباقي الأعمدة تُكتشف تلقائياً من العناوين. */
export const CLIENTS_FLAT_IMPORT_FIELDS: ExpectedField[] = [
  {
    key: "phone",
    label: "رقم الهاتف",
    required: true,
    aliases: [
      "موبايل",
      "جوال",
      "هاتف",
      "الهاتف",
      "رقم الهاتف",
      "رقم هاتف",
      "هاتف العميل",
      "رقم التليفون",
      "رقم التلفون",
      "تليفون",
      "تلفون",
      "رقم الجوال",
      "رقم الموبايل",
      "هاتف محمول",
      "رقم تليفون",
      "رقم تلفون",
      "mobile",
      "phone",
      "tel",
    ],
  },
  {
    key: "name",
    label: "اسم الشركة / الاسم",
    required: false,
    aliases: [
      "اسم العميل",
      "اسم الشركة",
      "الاسم",
      "اسم العميل بالكامل",
      "الشركة",
      "اسم المنشأة",
      "customer name",
      "company name",
    ],
  },
  {
    key: "company",
    label: "اسم المسؤول / الشركة المعروضة",
    required: false,
    aliases: [
      "اسم المسؤول",
      "المسؤول",
      "جهة الاتصال",
      "اسم صاحب الشركة",
      "الشركة المعروضة",
      "contact person",
    ],
  },
  {
    key: "activity",
    label: "النشاط",
    required: false,
    aliases: ["نوع النشاط", "مجال العمل", "القطاع", "activity"],
  },
  {
    key: "position",
    label: "الوظيفة",
    required: false,
    aliases: ["المسمى الوظيفي", "المنصب", "job title", "title"],
  },
  {
    key: "address",
    label: "العنوان",
    required: false,
    aliases: ["مكان العمل", "الموقع", "address"],
  },
  {
    key: "quotePrice",
    label: "عرض السعر",
    required: false,
    aliases: ["السعر", "التسعيرة", "عرض سعر", "quote"],
  },
  {
    key: "allowedDiscount",
    label: "الخصم الممنوح / نص",
    required: false,
    aliases: ["الخصم", "نسبة الخصم", "discount"],
  },
  {
    key: "salesNotes",
    label: "ملاحظات",
    required: false,
    aliases: ["ملاحظات المبيعات", "تعليقات", "notes", "remarks"],
  },
  {
    key: "sourceAdName",
    label: "اسم الإعلان",
    required: false,
    aliases: ["الإعلان", "اسم الاعلان", "ad name", "campaign"],
  },
  {
    key: "adPlatform",
    label: "قناة التسويق",
    required: false,
    aliases: ["منصة الإعلان", "مصدر العميل", "القناة", "platform", "source"],
  },
  {
    key: "visitAppointmentScheduled",
    label: "تم اجتماع / زيارة مجدولة (نعم/لا)",
    required: false,
    aliases: [
      "زيارة مجدولة",
      "اجتماع مجدول",
      "موعد زيارة",
      "visit scheduled",
    ],
  },
  {
    key: "visitAppointmentDate",
    label: "تاريخ الزيارة",
    required: false,
    aliases: ["موعد الزيارة", "تاريخ الموعد", "visit date"],
  },
  {
    key: "presentingEmployeeName",
    label: "موظف المبيعات",
    required: false,
    aliases: [
      "مندوب المبيعات",
      "مسؤول المبيعات",
      "البائع",
      "sales rep",
      "salesperson",
    ],
  },
  {
    key: "lossReason",
    label: "سبب الإغلاق",
    required: false,
    aliases: ["سبب الخسارة", "سبب الرفض", "loss reason"],
  },
  {
    key: "qqAnswer",
    label: "QQ (نعم/لا)",
    required: false,
    aliases: ["QQ", "سؤال الجودة"],
  },
  {
    key: "currentSituation",
    label: "الموقف الحالي",
    required: false,
    aliases: ["الحالة", "الوضع الحالي", "status"],
  },
  {
    key: "managementRecommendationText",
    label: "توصيات الاجتماع",
    required: false,
    aliases: [
      "توصيات الإدارة",
      "توصية الإدارة",
      "ملاحظات الإدارة",
      "recommendation",
    ],
  },
  {
    key: "managementRecommendationDate",
    label: "تاريخ التوصية / تاريخ اليوم",
    required: false,
    aliases: ["تاريخ التوصية", "تاريخ اليوم", "recommendation date"],
  },
  {
    key: "clientWarmingText",
    label: "تعليمات Warming",
    required: false,
    aliases: ["Warming", "تعليمات التسخين", "نص warming"],
  },
  {
    key: "initialCallDate",
    label: "تاريخ أول اتصال",
    required: false,
    aliases: ["أول اتصال", "تاريخ الاتصال الأول", "first call"],
  },
  {
    key: "nextFollowUpAt",
    label: "متابعة تالية",
    required: false,
    aliases: [
      "موعد المتابعة",
      "تاريخ المتابعة",
      "المتابعة القادمة",
      "next follow up",
    ],
  },
  {
    key: "followUpSlots",
    label: "متابعات (JSON، اختياري — قديم)",
    required: false,
    aliases: ["متابعات", "follow ups json", "followups"],
  },
  {
    key: "followUpSlot1Note",
    label: followUpSlotNoteHeaderAr(1),
    required: false,
    aliases: followUpSlotNoteHeaderAliases(1),
  },
  {
    key: "followUpSlot1Date",
    label: followUpSlotDateHeaderAr(1),
    required: false,
    aliases: followUpSlotDateHeaderAliases(1),
  },
  {
    key: "clientType",
    label: "نوع العميل (TB/TU/TC…)",
    required: false,
    aliases: ["نوع العميل", "تصنيف العميل", "client type", "type"],
  },
  {
    key: "daysCount",
    label: "عدد الأيام / نص مخصص",
    required: false,
    aliases: ["عدد الأيام", "أيام", "days"],
  },
];
